spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: file-server
          uri: lb:http://FILE-SERVER
          predicates:
            - Path=/api/v1/bucket/**
        - id: scheduling-server
          uri: lb:http://SCHEDULING-SERVER
          predicates:
            - Path=/api/v1/scheduling/**
        - id: notification-server
          uri: lb:http://NOTIFICATION-SERVER
          predicates:
            - Path=/api/v1/notification/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_JWT_ISSUER_URI}
server:
  port: 8080
