spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: file-server
          uri: lb:http://FILE-SERVER
          predicates:
            - Path=/api/v1/bucket/**
        - id: scheduling-server
          uri: lb:http://SCHEDULING-SERVER
          predicates:
            - Path=/api/v1/scheduling/**
        - id: notification-server
          uri: lb:http://NOTIFICATION-SERVER
          predicates:
            - Path=/api/v1/notification/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_JWT_ISSUER_URI}
server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/infrastructure/api-gateway/application.log
  level:
    com.azsumtoshko.api_gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,env,metrics,trace,loggers,httptrace
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
