# Shared in all configurations
spring:
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,env,metrics,trace,loggers,httptrace
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    path: /app/logs
    name: /app/logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"