spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/scheduling
    username: AzSumToshko
    password: Admin123123!
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz:
        threadPool:
          threadCount: 5
        scheduler:
          instanceName: ClusteredQuartzScheduler
          instanceId: AUTO
        jobStore:
          class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
          driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          isClustered: true
          clusterCheckinInterval: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 3333
