server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Configuration for Spring Boot application logs
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot
          __path__: /var/log/spring-boot/**/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  # Configuration for infrastructure service logs
  - job_name: infrastructure-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: infrastructure
          service: config-server
          __path__: /var/log/infrastructure/config-server/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  - job_name: discovery-server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: infrastructure
          service: discovery-server
          __path__: /var/log/infrastructure/discovery-server/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  - job_name: api-gateway-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: infrastructure
          service: api-gateway
          __path__: /var/log/infrastructure/api-gateway/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  - job_name: notification-server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: infrastructure
          service: notification-server
          __path__: /var/log/infrastructure/notification-server/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  - job_name: file-server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: infrastructure
          service: file-server
          __path__: /var/log/infrastructure/file-server/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  - job_name: scheduling-server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: infrastructure
          service: scheduling-server
          __path__: /var/log/infrastructure/scheduling-server/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  # Configuration for business service logs
  - job_name: task-service-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: business-services
          service: task-service
          __path__: /var/log/services/task-service/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'
      - labels:
          level:
          logger:
          thread:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
          location: UTC

  # Configuration for Docker container logs (fallback)
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/log/containers/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            message: log
            container_name: attrs.tag
      - labels:
          container_name:
      - timestamp:
          source: timestamp
          format: RFC3339Nano 