spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/your-org/config-repo.git
#          search-paths: config
#          username: your-git-username       # If private repo
#          password: your-git-password       # Use secrets or env vars for these
        native:
          search-locations: classpath:/configurations
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/infrastructure/config-server/application.log
  level:
    com.azsumtoshko.config_server: INFO

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,env,metrics,trace,loggers,httptrace
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true